const es: Record<string, string> = {
  "Accept": "Aceptar",
  "Accepted": "Aceptado",
  "Access approvals": "Aprobaciones de acceso",
  "Access type": "Tipo de acceso",
  "Account": "Cuenta",
  "Action required": "Acción requerida",
  "Actions": "Acciones",
  "Actions locked": "Acciones bloqueadas",
  "Active job": "Trabajo activo",
  "Active Job": "Trabajo activo",
  "Active technicians": "Técnicos activos",
  "Active": "Activo",
  "Activity": "Actividad",
  "Add Note": "Agregar nota",
  "Add to Home Screen": "Agregar a la pantalla de inicio",
  "Address or landmark": "Dirección o punto de referencia",
  "Address or nearby landmark": "Dirección o punto de referencia cercano",
  "Address pending": "Dirección pendiente",
  "Address": "Dirección",
  "Admin": "Administración",
  "Affiliated example": "Ejemplo afiliado",
  "Affiliated technician": "Técnico afiliado",
  "Age": "Antigüedad",
  "Alarm on": "Alarma activa",
  "Alarm": "Alarma",
  "All customer contact is masked through ClueXP.": "Todo contacto con el cliente está protegido por ClueXP.",
  "All documents": "Todos los documentos",
  "All systems operational": "Todos los sistemas operativos",
  "All": "Todos",
  "Anonymous capacity": "Capacidad anónima",
  "Append-only audit": "Auditoría inmutable",
  "Approval needed": "Aprobación necesaria",
  "Approval received": "Aprobación recibida",
  "Approval": "Aprobación",
  "Approvals": "Aprobaciones",
  "Approve final price": "Aprobar precio final",
  "Approve": "Aprobar",
  "Approval activates dispatch eligibility only when the backend verification rules succeed.": "La aprobación activa la elegibilidad de despacho solo cuando se cumplen las verificaciones del servidor.",
  "Area": "Zona",
  "Arrival verification": "Verificación de llegada",
  "Arrival": "Llegada",
  "Arrived": "Llegó",
  "Assign from Map": "Asignar desde el mapa",
  "Assign Technician": "Asignar técnico",
  "Assign": "Asignar",
  "Assigned": "Asignado",
  "At-risk requests will appear here.": "Las solicitudes en riesgo aparecerán aquí.",
  "At-risk strip": "Solicitudes en riesgo",
  "Audit Log": "Registro de auditoría",
  "Auto accept eligible jobs": "Aceptar automáticamente trabajos elegibles",
  "Availability": "Disponibilidad",
  "Available now": "Disponible ahora",
  "Available teams": "Equipos disponibles",
  "Available": "Disponible",
  "Awaiting assignment": "Esperando asignación",
  "Awaiting org": "Esperando organización",
  "Back to Queue": "Volver a la cola",
  "Background check": "Verificación de antecedentes",
  "Background GPS": "GPS en segundo plano",
  "Blocking documents would prevent availability and auto accept.": "Los documentos bloqueantes impiden la disponibilidad y la aceptación automática.",
  "Blocking": "Bloqueante",
  "Business": "Negocio",
  "Busy with current job": "Ocupado con el trabajo actual",
  "Busy": "Ocupado",
  "Call a person instead": "Llamar a una persona",
  "Call Customer": "Llamar al cliente",
  "Call customer": "Llamar al cliente",
  "Call Technician": "Llamar al técnico",
  "Call technician": "Llamar al técnico",
  "Call": "Llamar",
  "Cancel": "Cancelar",
  "Cancelled": "Cancelado",
  "Cancellation policy": "Política de cancelación",
  "Capacity full": "Capacidad completa",
  "Capture payment": "Cobrar pago",
  "Category": "Categoría",
  "Chat": "Chat",
  "Choose verified access technician": "Elegir técnico de acceso verificado",
  "Clear price": "Precio claro",
  "Close": "Cerrar",
  "Closed": "Cerrado",
  "Closeout summary": "Resumen de cierre",
  "Complete job": "Completar trabajo",
  "Complete": "Completar",
  "Completed": "Completado",
  "Completion Rate": "Tasa de finalización",
  "Compliance Matrix": "Matriz de cumplimiento",
  "Compliance": "Cumplimiento",
  "Confirm arrival": "Confirmar llegada",
  "Confirm payment": "Confirmar pago",
  "Console status board": "Tablero de estado operativo",
  "Contact Customer": "Contactar al cliente",
  "Contact Technician": "Contactar al técnico",
  "Continue to payment": "Continuar al pago",
  "Continue": "Continuar",
  "Create Request": "Crear solicitud",
  "Create request": "Crear solicitud",
  "Creating...": "Creando...",
  "Critical alerts": "Alertas críticas",
  "Current workspace": "Espacio de trabajo actual",
  "Customer and access context": "Contexto del cliente y acceso",
  "Customer approval": "Aprobación del cliente",
  "Customer arrival PIN": "PIN de llegada del cliente",
  "Customer channel": "Canal del cliente",
  "Customer Chat": "Chat con el cliente",
  "Customer code": "Código del cliente",
  "Customer confirmation needed": "Se necesita confirmación del cliente",
  "Customer display name": "Nombre visible del cliente",
  "Customer name": "Nombre del cliente",
  "Customer owner": "Responsable del cliente",
  "Customer Owner": "Responsable del cliente",
  "Customer phone": "Teléfono del cliente",
  "Customer safe-name": "Nombre protegido del cliente",
  "Customer": "Cliente",
  "Dashboard": "Panel",
  "Decline Offer": "Rechazar oferta",
  "Decline with Reason": "Rechazar con motivo",
  "Decline": "Rechazar",
  "Declined": "Rechazado",
  "Delivery failed": "Entrega fallida",
  "Disabled": "Desactivado",
  "Dispatch area": "Zona de despacho",
  "Dispatch Board": "Tablero de despacho",
  "Dispatch channel": "Canal de despacho",
  "Dispatch control": "Control de despacho",
  "Dispatch Dashboard": "Panel de despacho",
  "Dispatch feed unavailable": "No se puede cargar el despacho",
  "Dispatch feed": "Ofertas de servicio",
  "Dispatch mode": "Modo de despacho",
  "Dispatch Policy": "Política de despacho",
  "Dispatch preferences": "Preferencias de despacho",
  "Dispatch": "Despacho",
  "Dispatcher": "Despachador",
  "Distance": "Distancia",
  "Docs blocked": "Bloqueado por documentos",
  "Documents": "Documentos",
  "Done": "Listo",
  "Draft configuration": "Configuración preliminar",
  "Earnings": "Ganancias",
  "Eligible": "Elegible",
  "Email": "Correo electrónico",
  "Emergency alerts": "Alertas de emergencia",
  "En route": "En camino",
  "Enter Network Ops": "Entrar a operaciones",
  "Enter Provider Console": "Entrar al portal de proveedores",
  "Entity": "Entidad",
  "Escalate": "Escalar",
  "Escalated": "Escalado",
  "Escalation audit trail": "Historial de escalamiento",
  "Escalation Queue": "Cola de escalamiento",
  "Escalations": "Escalamientos",
  "Estimate": "Estimado",
  "Estimated range": "Rango estimado",
  "ETA": "Tiempo estimado",
  "Event timeline": "Cronología de eventos",
  "Event trail": "Historial de eventos",
  "Expired": "Vencido",
  "Expiring": "Por vencer",
  "Export shift report": "Exportar informe del turno",
  "Export": "Exportar",
  "Field Map": "Mapa de campo",
  "Filter requests": "Filtrar solicitudes",
  "Filters": "Filtros",
  "Final": "Final",
  "Finance": "Finanzas",
  "First accept wins": "La primera aceptación gana",
  "Fulfillment policy": "Política de cumplimiento",
  "Fulfillment": "Cumplimiento",
  "Full name": "Nombre completo",
  "Go online": "Conectarse",
  "GPS live": "GPS activo",
  "GPS stale": "GPS desactualizado",
  "GPS": "GPS",
  "History": "Historial",
  "Hold": "Poner en espera",
  "Identity": "Identidad",
  "In service": "En servicio",
  "Inactive": "Inactivo",
  "Incoming job request": "Solicitud de trabajo entrante",
  "Incoming offer": "Oferta entrante",
  "Individual technician": "Técnico independiente",
  "Individual": "Independiente",
  "Insurance status": "Estado del seguro",
  "Integrity verified": "Integridad verificada",
  "Internal notes": "Notas internas",
  "Job context": "Contexto del trabajo",
  "Job review": "Reseña del trabajo",
  "Jobs": "Trabajos",
  "Language": "Idioma",
  "Last verified": "Última verificación",
  "Live Dispatch Queue": "Cola de despacho en vivo",
  "Live queue preview": "Vista previa de la cola",
  "Live Queue": "Cola activa",
  "Live Requests": "Solicitudes activas",
  "Location": "Ubicación",
  "Map": "Mapa",
  "Mark arrived": "Marcar llegada",
  "Mark Resolved": "Marcar resuelto",
  "Masked Call": "Llamada protegida",
  "Masked capacity by area": "Capacidad protegida por zona",
  "Masked Internet Call": "Llamada de internet protegida",
  "Masked": "Protegido",
  "Matched customer": "Cliente asignado",
  "Mediated": "Protegido",
  "Message / Call": "Mensaje / llamada",
  "Message": "Mensaje",
  "Messages": "Mensajes",
  "Metadata": "Metadatos",
  "Missing skill": "Falta habilidad",
  "Mock reason": "Motivo de demostración",
  "Navigate": "Navegar",
  "Navigation": "Navegación",
  "Nearby assigned work": "Trabajos asignados cercanos",
  "Nearby service area": "Zona de servicio cercana",
  "Nearby work": "Trabajo cercano",
  "Network bidding": "Licitación de red",
  "Network capacity map": "Mapa de capacidad de la red",
  "Network governance": "Gobernanza de la red",
  "Network open": "Red abierta",
  "Network overflow": "Desbordamiento de red",
  "Network release preview": "Vista previa de liberación a la red",
  "Network routed": "Enrutado por la red",
  "Network routing and ownership": "Enrutamiento y responsabilidad",
  "Network routing eligible": "Elegible para enrutamiento",
  "Network": "Red",
  "New Service Request": "Nueva solicitud de servicio",
  "New": "Nuevo",
  "Next stop": "Próxima parada",
  "No active job": "No hay trabajo activo",
  "No active requests": "No hay solicitudes activas",
  "No named technician yet": "Aún no hay técnico asignado",
  "No pending approvals": "No hay aprobaciones pendientes",
  "No records match the current filters.": "Ningún registro coincide con los filtros actuales.",
  "No safety flags": "Sin alertas de seguridad",
  "No SLA exposure": "Sin riesgo de SLA",
  "Notifications": "Notificaciones",
  "Off": "Desactivado",
  "Offer closed": "Oferta cerrada",
  "Offer expires": "La oferta vence",
  "Offer expiring": "Oferta por vencer",
  "Offer sent": "Oferta enviada",
  "Offline": "Desconectado",
  "On site": "En el sitio",
  "Online": "En línea",
  "Open live tracking": "Abrir seguimiento en vivo",
  "Open queue": "Abrir cola",
  "Open": "Abrir",
  "Operations map": "Mapa de operaciones",
  "Operations": "Operaciones",
  "Optional comment": "Comentario opcional",
  "Organization intake": "Ingreso de organización",
  "Organization managed": "Gestionado por la organización",
  "Organization roster": "Personal de la organización",
  "Organization": "Organización",
  "Organizations": "Organizaciones",
  "Origin": "Origen",
  "Outside area": "Fuera de zona",
  "Override Block": "Anular bloqueo",
  "Override needed": "Requiere anulación",
  "Page 1 of 1": "Página 1 de 1",
  "Pay": "Pago",
  "Pending applicant": "Solicitante pendiente",
  "Pending jobs": "Trabajos pendientes",
  "Pending network assignment": "Asignación de red pendiente",
  "Pending review": "Revisión pendiente",
  "Pending": "Pendiente",
  "Platform admin": "Administrador de plataforma",
  "Phone": "Teléfono",
  "PII masked": "Datos personales protegidos",
  "Platform Operations Sign In": "Acceso a operaciones de plataforma",
  "Policy preview": "Vista previa de la política",
  "Privacy safe": "Privacidad protegida",
  "Production": "Producción",
  "Profile tools": "Herramientas del perfil",
  "Profile": "Perfil",
  "Provider Console Sign In": "Acceso al portal de proveedores",
  "Provider": "Proveedor",
  "Provisional": "Provisional",
  "Push": "Notificaciones",
  "PWA": "Aplicación web",
  "Rank": "Posición",
  "Ranking inputs": "Factores de clasificación",
  "Rating": "Calificación",
  "Ready": "Listo",
  "Reassign": "Reasignar",
  "Recent activity": "Actividad reciente",
  "Refresh": "Actualizar",
  "Reject": "Rechazar",
  "Release to Network": "Liberar a la red",
  "Reports": "Informes",
  "Request customer approval": "Solicitar aprobación del cliente",
  "Request details": "Detalles de la solicitud",
  "Request Network Overflow": "Solicitar capacidad de la red",
  "Request Update": "Solicitar actualización",
  "Request": "Solicitud",
  "Requests": "Solicitudes",
  "Registration decision": "Decisión de registro",
  "Registration ID": "ID de registro",
  "Technician": "Técnico",
  "UUID from registration or audit event": "UUID del registro o evento de auditoría",
  "Approve or reject a pending technician or provider organization by its registration ID.": "Aprueba o rechaza un técnico u organización proveedora pendiente usando su ID de registro.",
  "IDs are available in the registration response and platform audit trail.": "Los ID aparecen en la respuesta de registro y en el historial de auditoría.",
  "Approximate service area": "Zona de servicio aproximada",
  "Return to jobs": "Volver a trabajos",
  "Review No-Solicit Terms": "Revisar términos de no captación",
  "Review work": "Revisar trabajo",
  "Risk": "Riesgo",
  "Route guidance": "Guía de ruta",
  "Route to Provider": "Enviar al proveedor",
  "Route to Team": "Enviar al equipo",
  "Route": "Enrutar",
  "Routed to org": "Enrutado a organización",
  "Safety check": "Verificación de seguridad",
  "Save Draft Preview": "Guardar vista preliminar",
  "Save Draft": "Guardar borrador",
  "Search requests, technicians, organizations": "Buscar solicitudes, técnicos u organizaciones",
  "Seen": "Visto",
  "Select provider organization": "Seleccionar organización proveedora",
  "Selected photos": "Fotos seleccionadas",
  "Send message": "Enviar mensaje",
  "Send Offer": "Enviar oferta",
  "Sent": "Enviado",
  "Service address": "Dirección del servicio",
  "Service checklist": "Lista de servicio",
  "Service request": "Solicitud de servicio",
  "Service": "Servicio",
  "Session required": "Sesión requerida",
  "Settings": "Configuración",
  "Sign in": "Iniciar sesión",
  "Sign out": "Cerrar sesión",
  "Situation": "Situación",
  "Skip": "Omitir",
  "SLA risk": "Riesgo de SLA",
  "Sound alarm": "Alarma sonora",
  "Source channel": "Canal de origen",
  "Specialist": "Especialista",
  "Stale GPS": "GPS desactualizado",
  "Standing by": "En espera",
  "Start navigation": "Iniciar navegación",
  "Start service": "Iniciar servicio",
  "Status timeline": "Cronología de estado",
  "Status": "Estado",
  "Subscription blocked": "Suscripción bloqueada",
  "Superseded": "Sustituido",
  "Suspend": "Suspender",
  "Suspended": "Suspendido",
  "Switch workspace": "Cambiar espacio de trabajo",
  "System state": "Estado del sistema",
  "System": "Sistema",
  "Take Ownership": "Asumir responsabilidad",
  "Team": "Equipo",
  "Teams": "Equipos",
  "Technicians": "Técnicos",
  "Tenant auth": "Acceso seguro",
  "Tenant policy preview": "Vista previa de política",
  "Time": "Hora",
  "Timestamp": "Fecha y hora",
  "Today": "Hoy",
  "Too far away": "Demasiado lejos",
  "Trust & safety": "Confianza y seguridad",
  "Trust profile": "Perfil de confianza",
  "Trust state": "Estado de confianza",
  "Trust": "Confianza",
  "Type masked message": "Escribir mensaje protegido",
  "Type": "Tipo",
  "Unchanged": "Sin cambios",
  "Unavailable": "No disponible",
  "Urgency": "Urgencia",
  "Urgent Service Dispatch": "Despacho de servicio urgente",
  "Urgent service request": "Solicitud de servicio urgente",
  "Value": "Valor",
  "Verification required": "Verificación requerida",
  "Verification pending": "Verificación pendiente",
  "Verified entities": "Entidades verificadas",
  "Verified network capacity": "Capacidad verificada de la red",
  "Verified phone": "Teléfono verificado",
  "Verified professional": "Profesional verificado",
  "Verified": "Verificado",
  "View Profile": "Ver perfil",
  "View": "Ver",
  "Waiting": "Esperando",
  "Welcome": "Bienvenido",
  "Which situation fits best?": "¿Qué situación describe mejor el problema?",
  "Why decline?": "¿Por qué rechazas?",
  "Why this rank": "Motivo de esta posición",
  "Withdraw Preview": "Retirar vista preliminar",
  "Work started": "Trabajo iniciado",
  "Working...": "Procesando...",
  "Workspace": "Espacio de trabajo",
  "Wrong skill or equipment": "Habilidad o equipo incorrecto",
  "Year": "Año",
  "You are unavailable": "No estás disponible",
  "You": "Tú",

  "A few structured answers help us route the right access specialist without inventing details.": "Unas respuestas breves nos ayudan a enviar al especialista adecuado sin inventar detalles.",
  "Accepting creates an internal organization milestone. The customer is not MATCHED until a technician is assigned.": "Aceptar crea un hito interno de la organización. El cliente no queda ASIGNADO hasta que se nombre un técnico.",
  "Aggregated counts and ETA bands only. Names, exact coordinates, phone numbers, and provider identity stay hidden.": "Solo se muestran conteos agregados y rangos de llegada. Los nombres, coordenadas exactas, teléfonos e identidad del proveedor permanecen ocultos.",
  "Allow immediate trusted routing across eligible network supply.": "Permitir enrutamiento confiable inmediato entre proveedores elegibles.",
  "Approve/reject/suspend actions are platform-operator actions.": "Aprobar, rechazar y suspender son acciones del operador de plataforma.",
  "Area-level supply signals support routing decisions without exposing technician identity or exact location before assignment.": "Las señales de capacidad por zona ayudan a enrutar sin revelar la identidad ni ubicación exacta del técnico antes de asignarlo.",
  "Ask the specialist to show the same code.": "Pide al especialista que muestre el mismo código.",
  "Backend enforces first-accept-wins. If another technician accepts first, this screen must show the superseded offer state from the API.": "El servidor aplica que la primera aceptación gana. Si otro técnico acepta primero, esta pantalla mostrará que la oferta fue sustituida.",
  "Call-center entry for provider-owned requests. The backend creates the job with trusted org/session context, not a browser-supplied org id.": "Ingreso telefónico para solicitudes del proveedor. El servidor crea el trabajo usando la organización y sesión verificadas.",
  "Choose the operating model without changing origin or customer ownership.": "Elige el modelo operativo sin cambiar el origen ni la responsabilidad del cliente.",
  "Columns are console_status lanes. Trust-state appears only as a small per-card chip.": "Las columnas representan estados operativos. El estado de confianza aparece solo como una etiqueta pequeña.",
  "Completion cannot close until customer approval or authorized dispatcher override is recorded.": "El trabajo no puede cerrarse hasta registrar la aprobación del cliente o una anulación autorizada.",
  "Configure who manages dispatch and when a private provider queue may request verified network capacity. This preview does not persist changes.": "Configura quién gestiona el despacho y cuándo una cola privada puede solicitar capacidad verificada de la red. Esta vista previa no guarda cambios.",
  "Console status is the operator view. Trust-state is customer visibility and changes only when the backend assigns a named technician.": "El estado operativo es la vista del despachador. El estado visible al cliente solo cambia cuando el servidor asigna un técnico identificado.",
  "Create a provider organization access request.": "Solicita acceso para una organización proveedora.",
  "Customer: Can wait inside lobby. Needs arrival call.": "Cliente: puede esperar dentro del vestíbulo. Necesita una llamada al llegar.",
  "Demo call state. Production should use a provider such as Twilio/WebRTC and keep customer contact mediated.": "Estado de llamada de demostración. En producción, el contacto del cliente permanecerá protegido.",
  "Dense service-request table with trust-state separated from console status.": "Tabla compacta de solicitudes con el estado de confianza separado del estado operativo.",
  "Designed for phone and dispatcher-entered requests. Submit stores the customer under the authenticated provider tenant.": "Diseñado para solicitudes telefónicas ingresadas por despacho. Al enviar, el cliente se guarda bajo el proveedor autenticado.",
  "Earnings are mock settlement estimates.": "Las ganancias son estimaciones de liquidación.",
  "Exact customer phone remains mediated for privacy.": "El teléfono exacto del cliente permanece protegido.",
  "Factual reasons, ownership, and resolution actions for service requests needing human intervention.": "Motivos, responsables y acciones de resolución para solicitudes que necesitan intervención humana.",
  "Go online when you are ready for dispatch. ClueXP will pause offer alerts while offline.": "Conéctate cuando estés listo para recibir trabajos. ClueXP pausará las alertas mientras estés desconectado.",
  "Internal notes are separate from customer and technician messages. Organization acceptance does not create MATCHED.": "Las notas internas están separadas de los mensajes del cliente y técnico. La aceptación de la organización no asigna un técnico.",
  "Keep customer ownership with the origin organization while requesting verified external capacity.": "Mantén la responsabilidad del cliente con la organización de origen mientras solicitas capacidad externa verificada.",
  "Keep every request inside the organization roster.": "Mantener todas las solicitudes dentro del personal de la organización.",
  "Keep this page open for live updates.": "Mantén esta página abierta para recibir actualizaciones.",
  "License, insurance, authorization and business documents that control dispatch eligibility.": "Licencias, seguros, autorizaciones y documentos comerciales que controlan la elegibilidad de despacho.",
  "Live service requests, network capacity, SLA exposure, and recent trust-state activity.": "Solicitudes activas, capacidad de la red, riesgo de SLA y actividad reciente.",
  "Map is static mock data; no fabricated movement or routes.": "El mapa usa datos de demostración; no inventa movimientos ni rutas.",
  "Mock PIN entry. Production should support PIN, QR, and dispatcher override with audit reason.": "Ingreso de PIN de demostración. Producción admitirá PIN, QR y anulación del despachador con motivo auditado.",
  "Mock ranking explains distance, skill, availability, verification, and workload. It does not dispatch or override backend eligibility.": "La clasificación explica distancia, habilidad, disponibilidad, verificación y carga. No despacha ni anula la elegibilidad del servidor.",
  "Mock summary. Final amount is backend/provider-settlement controlled.": "Resumen de demostración. El monto final lo controla la liquidación del servidor y proveedor.",
  "Network release changes fulfillment search only. Origin and customer ownership remain attached to the request.": "Liberar a la red solo cambia la búsqueda de cumplimiento. El origen y responsable del cliente permanecen en la solicitud.",
  "New registration requests will appear here.": "Las nuevas solicitudes de registro aparecerán aquí.",
  "Notes are optional. Skip has the same weight here.": "Las notas son opcionales. Puedes omitirlas.",
  "Organization acceptance is not customer MATCHED. Wait for a named technician before changing the customer-visible state.": "Aceptar como organización no asigna al cliente. Espera a que haya un técnico identificado antes de cambiar el estado visible.",
  "Organization-scoped session for dispatchers and provider admins.": "Sesión limitada a la organización para despachadores y administradores.",
  "Photos can help, but they never block dispatch.": "Las fotos pueden ayudar, pero nunca bloquean el despacho.",
  "Plain-language support for this request. No app install required.": "Ayuda clara para esta solicitud. No necesitas instalar una aplicación.",
  "Priority requests float first. Open rows for the request drawer.": "Las solicitudes prioritarias aparecen primero. Abre una fila para ver sus detalles.",
  "Private by default with explicit, auditable release behavior.": "Privado por defecto, con liberación explícita y auditable.",
  "Production will send this reason to dispatch before the offer is released to another technician.": "Producción enviará este motivo a despacho antes de liberar la oferta a otro técnico.",
  "Rate the completed service. This affects the technician and fulfillment company when applicable.": "Califica el servicio completado. Esto afecta al técnico y a la empresa responsable cuando corresponda.",
  "Requests matching the current filters will appear here.": "Las solicitudes que coincidan con los filtros aparecerán aquí.",
  "Review pending individual technicians and provider organizations before activation.": "Revisa técnicos independientes y organizaciones proveedoras antes de activarlos.",
  "Review the completed service before capture.": "Revisa el servicio completado antes de cobrar.",
  "Routing creates an internal provider workflow. Customer trust-state remains INTAKE until a named technician is assigned.": "El enrutamiento crea un flujo interno del proveedor. El cliente permanece en INGRESO hasta que se asigne un técnico identificado.",
  "Secure access for verified ClueXP technicians.": "Acceso seguro para técnicos verificados de ClueXP.",
  "Search verified network capacity after a configured threshold or manual release.": "Buscar capacidad verificada de la red después del umbral configurado o una liberación manual.",
  "Set availability, keep GPS active, receive offer alarms, and work only from backend-confirmed assignments.": "Configura tu disponibilidad, mantén el GPS activo, recibe alertas y trabaja solo con asignaciones confirmadas.",
  "Sign in before creating provider requests.": "Inicia sesión antes de crear solicitudes del proveedor.",
  "Sign in with an authorized account before opening this console.": "Inicia sesión con una cuenta autorizada antes de abrir este portal.",
  "Sorted by stalled service requests, safety flags, age, and service pressure. Customer trust-state stays separate from console status.": "Ordenado por solicitudes detenidas, alertas de seguridad, antigüedad y demanda. El estado del cliente permanece separado del estado operativo.",
  "Static placeholder with service area, job/technician markers and staleness indicators.": "Mapa de referencia con zona de servicio, marcadores de trabajos y técnicos, e indicadores de actualización.",
  "Stay online with GPS active to receive nearby service offers.": "Mantente conectado con el GPS activo para recibir ofertas cercanas.",
  "Technician access requires identity and compliance verification.": "El acceso de técnico requiere verificación de identidad y cumplimiento.",
  "Technician channel: no assigned technician yet.": "Canal del técnico: aún no hay técnico asignado.",
  "The assignment below is returned by dispatch.": "La asignación siguiente fue confirmada por despacho.",
  "The network operator ranks eligible providers and independent technicians using trusted routing.": "El operador de red clasifica proveedores y técnicos independientes elegibles mediante enrutamiento confiable.",
  "The provider controls assignment from its private roster and may trigger overflow by policy.": "El proveedor controla la asignación desde su personal privado y puede solicitar capacidad externa según su política.",
  "The specialist should present the matching verification before work begins.": "El especialista debe mostrar la verificación correspondiente antes de comenzar.",
  "The specialist will verify ID or authority at arrival.": "El especialista verificará la identificación o autorización al llegar.",
  "This account is currently dispatched by ClueXP. Affiliated technicians may also be routed by their organization.": "Esta cuenta recibe despachos de ClueXP. Los técnicos afiliados también pueden ser enrutados por su organización.",
  "This commits your request and matches a specialist. Technician details appear only after the backend assigns someone.": "Esto confirma tu solicitud e inicia la asignación. Los datos del técnico aparecen solo después de que el servidor lo asigne.",
  "This is the first commercial consent step. No technician is committed before you accept.": "Este es el primer consentimiento comercial. No se asigna ningún técnico antes de que aceptes.",
  "Transparent mock weights for operator review. No auction or bidding.": "Factores transparentes para revisión operativa. No hay subastas ni licitaciones.",
  "Trust-state column uses only INTAKE, MATCHED, or FULFILLMENT. Severity and reasons stay separate.": "La columna de confianza solo usa INGRESO, ASIGNADO o CUMPLIMIENTO. La gravedad y los motivos permanecen separados.",
  "Use GPS if you can. A typed address is fine too.": "Usa el GPS si puedes. También puedes escribir una dirección.",
  "We are connecting you to a person who can help faster from here.": "Te estamos conectando con una persona que puede ayudarte más rápido.",
  "Your review is tied to this completed job. It helps future routing without changing customer ownership.": "Tu reseña está vinculada a este trabajo completado. Ayuda al enrutamiento futuro sin cambiar la responsabilidad del cliente.",
  "Your technician registration is awaiting ClueXP approval. Job offers remain unavailable until verification is complete.": "Tu registro de técnico está esperando la aprobación de ClueXP. Las ofertas no estarán disponibles hasta completar la verificación."
};

const patterns: Array<[RegExp, (...groups: string[]) => string]> = [
  [/^Step (\d+) of (\d+)$/, (step, total) => `Paso ${step} de ${total}`],
  [/^(\d+) done$/, (count) => `${count} completados`],
  [/^(\d+) min ETA$/, (count) => `${count} min de llegada`],
  [/^ETA (\d+)m$/, (count) => `Llegada ${count} min`],
  [/^Page (\d+) of (\d+)$/, (page, total) => `Página ${page} de ${total}`],
  [/^(\d+) minutes? without an assigned technician$/, (count) => `${count} minutos sin técnico asignado`],
  [/^(.+) urgency$/, (value) => `Urgencia ${translateUiText(value)}`],
  [/^(.+) pressure$/, (value) => `Demanda ${translateUiText(value)}`],
  [/^Technician is (online|offline)$/, (value) => `El técnico está ${value === "online" ? "en línea" : "desconectado"}`]
];

export function translateUiText(value: string): string {
  const leading = value.match(/^\s*/)?.[0] ?? "";
  const trailing = value.match(/\s*$/)?.[0] ?? "";
  const core = value.trim();
  if (!core) return value;
  const exact = es[core];
  if (exact) return `${leading}${exact}${trailing}`;
  for (const [pattern, render] of patterns) {
    const match = core.match(pattern);
    if (match) return `${leading}${render(...match.slice(1))}${trailing}`;
  }
  if (core.includes(" · ")) {
    return `${leading}${core.split(" · ").map((part) => translateUiText(part).trim()).join(" · ")}${trailing}`;
  }
  return value;
}
