from __future__ import annotations

from copy import deepcopy


DEFAULT_CLOSEOUT_ITEM_TYPES: list[dict] = [
    {
        "code": "service_fee",
        "label": "Service fee",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": True,
        "default_reimbursement_eligible": False,
        "requires_provided_by": False,
        "requires_note": False,
        "requires_receipt": False,
        "sort_order": 10,
    },
    {
        "code": "labor",
        "label": "Labor",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": True,
        "default_reimbursement_eligible": False,
        "requires_provided_by": False,
        "requires_note": False,
        "requires_receipt": False,
        "sort_order": 20,
    },
    {
        "code": "diagnostic",
        "label": "Diagnostic",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": True,
        "default_reimbursement_eligible": False,
        "requires_provided_by": False,
        "requires_note": False,
        "requires_receipt": False,
        "sort_order": 30,
    },
    {
        "code": "emergency_fee",
        "label": "Emergency fee",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": True,
        "default_reimbursement_eligible": False,
        "requires_provided_by": False,
        "requires_note": False,
        "requires_receipt": False,
        "sort_order": 40,
    },
    {
        "code": "trip_fee",
        "label": "Trip fee",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": True,
        "default_reimbursement_eligible": False,
        "requires_provided_by": False,
        "requires_note": False,
        "requires_receipt": False,
        "sort_order": 50,
    },
    {
        "code": "physical_part",
        "label": "Physical part",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": True,
        "requires_provided_by": True,
        "requires_note": False,
        "requires_receipt": False,
        "sort_order": 60,
    },
    {
        "code": "hardware",
        "label": "Hardware",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": True,
        "requires_provided_by": True,
        "requires_note": False,
        "requires_receipt": False,
        "sort_order": 70,
    },
    {
        "code": "key_blank",
        "label": "Key blank",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": True,
        "requires_provided_by": True,
        "requires_note": False,
        "requires_receipt": False,
        "sort_order": 80,
    },
    {
        "code": "remote_fob",
        "label": "Remote / fob",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": True,
        "requires_provided_by": True,
        "requires_note": False,
        "requires_receipt": False,
        "sort_order": 90,
    },
    {
        "code": "key_code_purchase",
        "label": "Key code purchase",
        "status": "active",
        "default_taxable": False,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": True,
        "requires_provided_by": True,
        "requires_note": True,
        "requires_receipt": True,
        "sort_order": 100,
    },
    {
        "code": "programming_token",
        "label": "Programming token",
        "status": "active",
        "default_taxable": False,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": True,
        "requires_provided_by": True,
        "requires_note": True,
        "requires_receipt": True,
        "sort_order": 110,
    },
    {
        "code": "software_license",
        "label": "Software / license",
        "status": "active",
        "default_taxable": False,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": True,
        "requires_provided_by": True,
        "requires_note": True,
        "requires_receipt": True,
        "sort_order": 120,
    },
    {
        "code": "consumable",
        "label": "Consumable",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": True,
        "requires_provided_by": True,
        "requires_note": False,
        "requires_receipt": False,
        "sort_order": 130,
    },
    {
        "code": "permit_fee",
        "label": "Permit fee",
        "status": "active",
        "default_taxable": False,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": False,
        "requires_provided_by": True,
        "requires_note": True,
        "requires_receipt": True,
        "sort_order": 140,
    },
    {
        "code": "third_party_service",
        "label": "Third-party service",
        "status": "active",
        "default_taxable": False,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": True,
        "requires_provided_by": True,
        "requires_note": True,
        "requires_receipt": True,
        "sort_order": 150,
    },
    {
        "code": "discount",
        "label": "Discount",
        "status": "active",
        "default_taxable": False,
        "default_compensation_eligible": True,
        "default_reimbursement_eligible": False,
        "requires_provided_by": False,
        "requires_note": True,
        "requires_receipt": False,
        "sort_order": 160,
    },
    {
        "code": "other",
        "label": "Other",
        "status": "active",
        "default_taxable": True,
        "default_compensation_eligible": False,
        "default_reimbursement_eligible": False,
        "requires_provided_by": True,
        "requires_note": True,
        "requires_receipt": False,
        "sort_order": 170,
    },
]


def default_closeout_item_types() -> list[dict]:
    return deepcopy(DEFAULT_CLOSEOUT_ITEM_TYPES)
